"""Generates runtime/symbian_ordinals.c: (library, ordinal) -> name for every Symbian API the runtime
implements, so imports can be resolved at load time from the game binary itself.

Ordinals come from EKA2L1's Symbian 6.1 export lists (third_party/eka2l1, GPL-3.0). Only public
API names/ordinals are emitted; nothing is derived from any game binary."""
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from resolve_imports import load_defs  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
ENTRY = re.compile(r'\{\s*"([a-z0-9_]+)"\s*,\s*"([^"]+)"\s*,\s*\w+\s*\}')


def main():
    libs = load_defs()
    rows, missing = set(), []
    for src in sorted((ROOT / "runtime").glob("*.c")):
        for lib, name in ENTRY.findall(src.read_text(encoding="utf-8", errors="replace")):
            if name.startswith("@"):
                continue  # registered by ordinal already
            names = libs.get(lib, [])
            if name in names:
                rows.add((lib, names.index(name) + 1, name))
            else:
                missing.append(f"{lib}:{name}")
    out = ['/* Generated by tools/gen_ordinals.py from EKA2L1 export lists (GPL-3.0). Do not edit. */',
           '#include "runtime.h"', '',
           'const SymbianOrdinal SYMBIAN_ORDINALS[] = {']
    out += [f'    {{"{lib}", {o}, "{n}"}},' for lib, o, n in sorted(rows)]
    out += ['    {0, 0, 0},', '};', '']
    (ROOT / "runtime/symbian_ordinals.c").write_text("\n".join(out))
    print(f"{len(rows)} ordinals written")
    for m in missing:
        print("  not found in export lists:", m)


if __name__ == "__main__":
    main()
